server.port=8080

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

limiter.token-bucket.capacity=5
limiter.token-bucket.refill-rate=1

limiter.fixed-window.capacity=5
limiter.fixed-window.window-size-ms=10000

limiter.sliding-window.capacity=5
limiter.sliding-window.window-size-ms=10000